In [2]:
"""
Author: Wouter Van Gansbeke

Main file for training auto-encoders and vaes
Licensed under the CC BY-NC 4.0 license (https://creativecommons.org/licenses/by-nc/4.0/)
"""

import os
import sys
sys.argv = sys.argv[:1]
import json
import hydra
import wandb
import builtins
from termcolor import colored
from datetime import datetime
from omegaconf import OmegaConf, DictConfig
from typing import Dict, Any
from termcolor import colored
import torch
import torch.multiprocessing as mp
import torch.distributed as dist
from diffusers import AutoencoderKL

from ldmseg.models import GeneralVAESeg
from ldmseg.trainers import TrainerAE
from ldmseg.utils import prepare_config, Logger, is_main_process

from hydra import initialize, compose
from main_worker_ae import main_worker

In [3]:
# -------------------------------------------------------------------------------
# Step 0: 清理 Notebook 自动传入的额外命令行参数
sys.argv = sys.argv[:1]

# -------------------------------------------------------------------------------
# Step 1: 使用 Hydra API 加载配置
# 请根据实际情况修改 config_path，例如你的配置文件存放在 "configs/" 文件夹下
with initialize(config_path="tools/configs/", job_name="config"):
    cfg = compose(config_name="config")
# 将 OmegaConf 对象转换为普通字典
cfg = OmegaConf.to_object(cfg)

# -------------------------------------------------------------------------------
# Step 2: 配置分块、组合与预处理
wandb.config = cfg
# 这里假设配置文件中存在以下键；如果不存在，请在配置文件中添加或使用 .get() 方法提供默认值
cfg_dist    = cfg['distributed']
cfg_dataset = cfg['datasets']
cfg_base    = cfg['base']
project_dir = cfg['setup']

# 合并 base 与数据集专用配置（让数据集配置覆盖 base 中的同名字段）
cfg_dataset = {**cfg_base, **cfg_dataset}

root_dir = os.path.join(cfg['env']['root_dir'], project_dir)
data_dir = cfg['env']['data_dir']

# 调用 prepare_config 进一步整理数据集配置，返回更新后的配置和项目名称
cfg_dataset, project_name = prepare_config(cfg_dataset, root_dir, data_dir, run_idx=cfg['run_idx'])
project_name = f"{cfg_dataset['train_db_name']}_{project_name}"
#print(colored(f"Project name: {project_name}", 'red'))

# -------------------------------------------------------------------------------
# Step 3: 配置分布式训练参数
# 若配置中 world_size 为 -1 且 dist_url 为 "env://" 则根据环境变量 WORLD_SIZE 更新配置
if cfg_dist['dist_url'] == "env://" and cfg_dist['world_size'] == -1:
    cfg_dist['world_size'] = int(os.environ.get("WORLD_SIZE", 1))
cfg_dist['distributed'] = cfg_dist['world_size'] > 1 or cfg_dist['multiprocessing_distributed']

# -------------------------------------------------------------------------------
# Step 4: Debug 模式下特殊设置
if cfg.get('debug', True):
    print(colored("Running in debug mode!", "red"))
    cfg_dist['world_size'] = 1
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'
    cfg_dataset['train_kwargs']['num_workers'] = 0
    cfg_dataset['train_kwargs']['train_num_steps']=1

ngpus_per_node = torch.cuda.device_count()
# 根据 GPU 数量调整世界大小
cfg_dist['world_size'] = ngpus_per_node * cfg_dist['world_size']
#print(colored(f"World size: {cfg_dist['world_size']}", 'blue'))

# -------------------------------------------------------------------------------
# Step 6: 启动训练
cfg_dataset['train_kwargs']['train_num_steps']=12000
cfg_dataset['lr_scheduler_kwargs']['warmup_iters']=200
if cfg.get('debug', True):
    # Debug 模式下直接调用 main_worker（单 GPU 单进程）
    main_worker(0, ngpus_per_node, cfg_dist, cfg_dataset, project_name)
else:
    # 非 Debug 模式下使用 mp.spawn 启动分布式训练（注意：Notebook 中多进程可能会有额外问题）
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, cfg_dist, cfg_dataset, project_name))

/tmp/ipykernel_128701/2398671844.py:8: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  with initialize(config_path="tools/configs/", job_name="config"):


Using current time as run identifier: 20250419_172947
Use GPU: 0 for printing
Starting distributed training
Initialized distributed training
{
    "backbone": "unet",
    "data_dir": "/root/autodl-tmp/video_sequence",
    "ema_kwargs": {
        "decay": 0.9999,
        "device": "cuda"
    },
    "ema_on": false,
    "eval_kwargs": {
        "batch_size": 16,
        "count_th": 512,
        "mask_th": 0.5,
        "num_workers": 2,
        "overlap_th": 0.5,
        "print_freq": 100,
        "vis_every": 5000
    },
    "eval_only": false,
    "fill_value": 0.5,
    "has_bg": false,
    "ignore_label": 0,
    "image_scaling_factor": 0.18215,
    "inpainting_strength": 0.0,
    "load_path": null,
    "log_file": "/root/autodl-tmp/Video-latent-diffusion-panoptic-segmentation/simple_diffusion/kitti/run_20250419_172947/logger.txt",
    "loss_kwargs": {
        "cost_class": 1.0,
        "cost_mask": 1.0,
        "importance_sample_ratio": 0.75,
        "num_points": 12544,
        "over

7it [00:06,  1.09it/s]
7it [00:14,  2.11s/it]


images saved
Evaluation for semantic segmentation - val set
mIoU is 0.00


100%|██████████| 7/7 [00:05<00:00,  1.34it/s]


KITTI 全景评价结果： {'pq': 0.0, 'sq': 0.0, 'rq': 0.0, 'iou_sum': 0.0, 'tp': 0, 'fp': 1350, 'fn': 518}
-------------------------
Starting epoch 0
tensor([-2.0155, -1.9916, -1.9596,  ...,  2.0532,  2.0718,  2.2396],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  4,  7,  8,  9, 10, 12, 13, 14, 15, 18], device='cuda:0')
Learning rate is set to: 0.000e+00
tensor([-2.1892, -2.0229, -2.0131,  ...,  2.0735,  2.1124,  2.2813],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 11, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-2.1248, -2.1174, -2.1164,  ...,  1.9745,  1.9844,  2.1609],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  4,  8, 10, 11, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-2.2309, -2.0667, -2.0577,  ...,  1.9904,  2.0419,  2.1823],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-2.1984, -2.1858, -2.1473,  ...,  2.0845,  2.0901,  2.0907],
       device='cuda:0', g

0it [00:00, ?it/s]

 tensor([ 0,  1,  8, 10, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-3.2786, -3.2685, -3.2646,  ...,  3.6742,  3.6859,  3.6876],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  1,  8, 10, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-3.3239, -3.3113, -3.3066,  ...,  3.6771,  3.6795,  3.6908],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 12, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-3.3280, -3.3255, -3.3247,  ...,  3.7481,  3.7625,  3.7627],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 11, 13, 14], device='cuda:0')
tensor([-3.3847, -3.3808, -3.3805,  ...,  3.7519,  3.7607,  3.7683],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-3.4031, -3.3946, -3.3937,  ...,  3.7751,  3.7896,  3.8033],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-3.5367, -3.5008, -3.4446,  ...,  3.7809, 

7it [00:04,  1.40it/s]
7it [00:09,  1.42s/it]


images saved
Evaluation for semantic segmentation - val set
mIoU is 0.27


100%|██████████| 7/7 [00:05<00:00,  1.37it/s]


KITTI 全景评价结果： {'pq': 0.0, 'sq': 0.0, 'rq': 0.0, 'iou_sum': 0.0, 'tp': 0, 'fp': 215, 'fn': 518}
Average loss: 3.844e+00
Epoch took 0:01:02.358073
ETA: 2:10:55.979853
-------------------------
Starting epoch 1
tensor([-4.6080, -4.5684, -4.5665,  ...,  3.5838,  3.5970,  3.6714],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 14, 15, 16, 17], device='cuda:0')
Learning rate is set to: 6.281e-05
tensor([-4.6321, -4.6166, -4.5976,  ...,  3.7657,  3.7716,  3.7977],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  1,  8,  9, 10, 12, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-4.8760, -4.8613, -4.8437,  ...,  4.0652,  4.0683,  4.0716],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 16, 17], device='cuda:0')
tensor([-4.9467, -4.8948, -4.8926,  ...,  4.3273,  4.3518,  4.3551],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  5,  8, 10, 14, 15, 16, 17], device='cuda:0')
tensor([-4.9716, -4.9551, -4.9391,  ...,  4.4

0it [00:00, ?it/s]

 tensor([ 0,  8, 10, 12, 13, 14, 16], device='cuda:0')
tensor([-6.2068, -6.2037, -6.1715,  ...,  6.9954,  7.0128,  7.0353],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-6.8925, -6.8153, -6.7797,  ...,  7.8300,  7.8895,  7.8996],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  2,  8, 10, 12, 13, 14, 17], device='cuda:0')
tensor([-6.1385, -6.1086, -6.0844,  ...,  6.6860,  6.6903,  6.7662],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8,  9, 10, 12, 13, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-5.8405, -5.8290, -5.8229,  ...,  5.9101,  5.9446,  5.9776],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 16, 17], device='cuda:0')
tensor([-6.2355, -6.2188, -6.1577,  ...,  7.3441,  7.3539,  7.3838],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  4,  8,  9, 10, 12, 13, 14, 15, 17, 18], device='cuda:0')
tensor([-5.9357, -5.9148, -5.8922,  ..

7it [00:04,  1.41it/s]
7it [00:10,  1.44s/it]


images saved
Evaluation for semantic segmentation - val set
mIoU is 2.36


100%|██████████| 7/7 [00:05<00:00,  1.36it/s]


KITTI 全景评价结果： {'pq': 0.0, 'sq': 0.0, 'rq': 0.0, 'iou_sum': 0.0, 'tp': 0, 'fp': 300, 'fn': 518}
Average loss: 2.285e+00
Epoch took 0:01:03.125268
ETA: 1:54:13.534607
-------------------------
Starting epoch 2
tensor([-6.0603, -5.9717, -5.9276,  ...,  5.9088,  5.9337,  5.9383],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 11, 14, 15, 16, 17], device='cuda:0')
Learning rate is set to: 1.000e-04
tensor([-7.1537, -7.1437, -7.0324,  ...,  6.9060,  6.9483,  6.9767],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 12, 13, 14, 17], device='cuda:0')
tensor([-6.7521, -6.7475, -6.7313,  ...,  6.2365,  6.2848,  6.3534],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 12, 13, 14, 17], device='cuda:0')
tensor([-6.4949, -6.4425, -6.4200,  ...,  6.2945,  6.4913,  6.5134],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-6.2644, -6.2103, -6.1979,  ...,  6.1147,  6.

0it [00:00, ?it/s]

 tensor([ 0,  4,  8, 10, 11, 12, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-6.5714, -6.4970, -6.4519,  ...,  5.7049,  5.7570,  5.7743],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 13, 14, 16], device='cuda:0')
tensor([-7.2756, -7.2227, -7.0614,  ...,  5.7943,  5.8149,  5.8196],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 16, 17], device='cuda:0')
tensor([-7.4058, -7.2917, -7.2281,  ...,  6.2295,  6.2316,  6.2794],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-7.4757, -7.4666, -7.4625,  ...,  6.0076,  6.0118,  6.0134],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  4,  8,  9, 10, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-8.0746, -7.8945, -7.8791,  ...,  7.7670,  7.9300,  7.9823],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 11, 12, 13, 14, 16, 17], device='cuda:0')
tensor([-7.4667, -7.4178, -7.3134,  ..

7it [00:05,  1.38it/s]
7it [00:10,  1.45s/it]


images saved
Evaluation for semantic segmentation - val set
mIoU is 2.52


100%|██████████| 7/7 [00:05<00:00,  1.33it/s]


KITTI 全景评价结果： {'pq': 0.0, 'sq': 0.0, 'rq': 0.0, 'iou_sum': 0.0, 'tp': 0, 'fp': 300, 'fn': 518}
Average loss: 2.023e+00
Epoch took 0:01:02.905310
ETA: 1:47:50.483511
-------------------------
Starting epoch 3
tensor([-7.5077, -7.3350, -7.2581,  ...,  6.9291,  6.9314,  6.9925],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 16, 17], device='cuda:0')
Learning rate is set to: 1.000e-04
tensor([-7.1124, -7.1063, -7.0661,  ...,  6.4947,  6.6424,  6.6703],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8,  9, 10, 13, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-7.7730, -7.7255, -7.6395,  ...,  6.5695,  6.7793,  6.8600],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 13, 14, 16, 17], device='cuda:0')
tensor([-7.4091, -7.3338, -7.2104,  ...,  6.9403,  6.9681,  7.0196],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 13, 14, 16, 17], device='cuda:0')
tensor([-7.5338, -7.4689, -7.4528,  ...,  7.7169,  7.7804

0it [00:00, ?it/s]

 tensor([ 0,  5,  8, 10, 14, 15, 16, 17], device='cuda:0')
tensor([-7.8451, -7.7861, -7.7589,  ...,  6.1694,  6.2107,  6.3659],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 15, 16, 17], device='cuda:0')
tensor([-7.5401, -7.4255, -7.4184,  ...,  5.7543,  5.7954,  5.8312],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  1,  8,  9, 10, 12, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-7.9006, -7.8887, -7.8746,  ...,  6.3151,  6.3570,  6.4563],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  4,  7,  8,  9, 10, 12, 13, 14, 15, 17, 18], device='cuda:0')
tensor([-7.7855, -7.6774, -7.6355,  ...,  6.4163,  6.4565,  6.5360],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 11, 12, 13, 14, 16, 17], device='cuda:0')
tensor([-7.8065, -7.6909, -7.6343,  ...,  6.1963,  6.2156,  6.2780],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 12, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-7.5522, -

7it [00:04,  1.40it/s]
7it [00:09,  1.41s/it]


images saved
Evaluation for semantic segmentation - val set
mIoU is 2.88


100%|██████████| 7/7 [00:05<00:00,  1.35it/s]


KITTI 全景评价结果： {'pq': 0.0, 'sq': 0.0, 'rq': 0.0, 'iou_sum': 0.0, 'tp': 0, 'fp': 300, 'fn': 518}
Average loss: 1.906e+00
Epoch took 0:01:02.371140
ETA: 1:43:55.219767
-------------------------
Starting epoch 4
tensor([-7.9802, -7.8491, -7.7314,  ...,  5.9411,  6.0494,  6.1158],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  2,  4,  8, 10, 12, 13, 14, 17], device='cuda:0')
Learning rate is set to: 1.000e-04
tensor([-8.3078, -8.2163, -8.1921,  ...,  6.5095,  6.5204,  6.5221],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 12, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-7.4076, -7.3210, -7.3201,  ...,  5.5857,  5.5937,  5.6057],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 15, 16, 17], device='cuda:0')
tensor([-7.2630, -7.2456, -7.2079,  ...,  5.3883,  5.3939,  5.4246],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-7.6999, -7.6983, -7.6928,  .

0it [00:00, ?it/s]

 tensor([ 0,  8, 10, 11, 12, 14, 16, 17, 18], device='cuda:0')
tensor([-8.1657, -7.9925, -7.9485,  ...,  5.0586,  5.0970,  5.1698],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-7.5726, -7.5715, -7.5714,  ...,  5.1606,  5.1695,  5.2083],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-8.4144, -8.2713, -8.2521,  ...,  5.5488,  5.5539,  5.6047],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  5,  8, 10, 12, 13, 14, 16, 17], device='cuda:0')
tensor([-7.6253, -7.5738, -7.5724,  ...,  5.3364,  5.3628,  5.3729],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8,  9, 10, 13, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-7.9914, -7.9007, -7.8846,  ...,  5.2562,  5.2724,  5.3163],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 12, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-7.9523, -7.8956, -7.8

7it [00:04,  1.41it/s]
7it [00:09,  1.41s/it]


images saved
Evaluation for semantic segmentation - val set
mIoU is 3.31


100%|██████████| 7/7 [00:05<00:00,  1.35it/s]


KITTI 全景评价结果： {'pq': 0.0, 'sq': 0.0, 'rq': 0.0, 'iou_sum': 0.0, 'tp': 0, 'fp': 425, 'fn': 518}
Average loss: 1.872e+00
Epoch took 0:01:02.572933
ETA: 1:41:12.786212
-------------------------
Starting epoch 5
tensor([-8.4273, -8.3505, -8.2227,  ...,  5.1549,  5.1698,  5.2210],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  1,  3,  5,  8, 10, 12, 13, 14, 17], device='cuda:0')
Learning rate is set to: 1.000e-04
tensor([-8.3008, -8.2870, -8.2295,  ...,  4.8189,  4.8496,  5.0152],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8,  9, 10, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-8.6691, -8.4297, -8.4216,  ...,  5.2459,  5.2720,  5.3085],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  1,  8, 10, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-8.6793, -8.6373, -8.4071,  ...,  5.0387,  5.0389,  5.0652],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 16, 17], device='cuda:0')
tensor([-8.6822, -8.6602, -8.6193

0it [00:00, ?it/s]

 tensor([ 0,  8, 10, 14, 16, 17], device='cuda:0')
tensor([-11.0331, -10.8497, -10.7576,  ...,   4.8409,   4.8487,   4.9804],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 16, 17], device='cuda:0')
tensor([-11.3639, -11.3463, -11.3425,  ...,   5.3035,   5.3452,   5.3554],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 16, 17], device='cuda:0')
tensor([-10.7289, -10.4225, -10.3993,  ...,   4.9658,   5.0480,   5.0565],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8,  9, 10, 12, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-12.3634, -12.3092, -12.2642,  ...,   5.0896,   5.1744,   5.2719],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  5,  8, 10, 14, 15, 16, 17], device='cuda:0')
tensor([-11.3602, -11.3030, -11.2904,  ...,   3.7929,   3.8125,   4.0072],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  3,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-12.

7it [00:04,  1.44it/s]
7it [00:09,  1.40s/it]


images saved
Evaluation for semantic segmentation - val set
mIoU is 4.43


100%|██████████| 7/7 [00:05<00:00,  1.35it/s]


KITTI 全景评价结果： {'pq': 0.0, 'sq': 0.0, 'rq': 0.0, 'iou_sum': 0.0, 'tp': 0, 'fp': 596, 'fn': 518}
Average loss: 1.501e+00
Epoch took 0:01:02.195261
ETA: 1:38:57.973909
-------------------------
Starting epoch 6
tensor([-13.5907, -13.5544, -13.5423,  ...,   5.1754,   5.2485,   5.2531],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8,  9, 10, 12, 13, 14, 16, 17], device='cuda:0')
Learning rate is set to: 1.000e-04
tensor([-13.6368, -13.5688, -13.5231,  ...,   4.6356,   4.6510,   4.8450],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-13.4549, -13.3522, -13.3008,  ...,   4.5529,   4.6416,   4.6818],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-14.8049, -14.7998, -14.7310,  ...,   4.8319,   4.8741,   4.9061],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 11, 12, 13, 14, 16, 17], device='cu

0it [00:00, ?it/s]

 tensor([ 0,  8, 10, 14, 16, 17], device='cuda:0')
tensor([-23.2715, -22.9684, -22.7492,  ...,   4.6297,   4.6705,   4.8756],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 11, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-23.9688, -23.6795, -23.2029,  ...,   4.0914,   4.3507,   4.3828],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  3,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-24.7012, -24.1755, -23.8772,  ...,   5.2056,   5.3578,   5.5186],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8,  9, 10, 12, 13, 14, 15, 17], device='cuda:0')
tensor([-23.6597, -23.5864, -23.5796,  ...,   5.4294,   5.4626,   5.5634],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  1,  8,  9, 10, 12, 14, 15, 16, 17], device='cuda:0')
tensor([-23.6936, -23.5529, -23.4268,  ...,   5.1398,   5.1870,   5.3320],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 12, 13, 14, 16, 17, 18], devic

7it [00:04,  1.42it/s]
7it [00:09,  1.41s/it]


images saved
Evaluation for semantic segmentation - val set
mIoU is 6.03


100%|██████████| 7/7 [00:05<00:00,  1.38it/s]


KITTI 全景评价结果： {'pq': 0.0, 'sq': 0.0, 'rq': 0.0, 'iou_sum': 0.0, 'tp': 0, 'fp': 596, 'fn': 518}
Average loss: 1.074e+00
Epoch took 0:01:02.534704
ETA: 1:37:08.224844
-------------------------
Starting epoch 7
tensor([-26.0876, -25.7810, -25.6950,  ...,   4.9134,   4.9430,   5.0088],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  4,  8, 10, 13, 14, 15, 16, 17], device='cuda:0')
Learning rate is set to: 1.000e-04
tensor([-24.8399, -24.7417, -24.4604,  ...,   6.0100,   6.0349,   6.1792],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-25.6191, -24.8494, -24.1506,  ...,   4.5906,   4.6730,   4.7624],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  4,  8, 10, 11, 12, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-23.3384, -23.1036, -23.0239,  ...,   3.5689,   3.5985,   3.6712],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  3,  8, 10, 11, 13, 14, 15, 16, 17, 18], device

0it [00:00, ?it/s]


tensor([-26.6291, -26.5524, -25.7318,  ...,   5.6685,   5.7405,   5.8575],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8,  9, 10, 12, 13, 14, 15, 16, 17], device='cuda:0')
tensor([-28.9231, -28.8120, -28.7727,  ...,   4.7759,   4.8050,   4.8338],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  2,  8, 10, 12, 13, 14, 17], device='cuda:0')
tensor([-27.5363, -27.3871, -26.2879,  ...,   4.2981,   4.3121,   4.3882],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 16, 17], device='cuda:0')
tensor([-27.0150, -26.9559, -26.8965,  ...,   4.2734,   4.3080,   4.4211],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 16, 17], device='cuda:0')
tensor([-27.5193, -27.4181, -27.1619,  ...,   3.8762,   3.8787,   3.8819],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 17], device='cuda:0')
tensor([-28.3742, -27.8836, -27.6658,  ...,   6.4412,   6.4544,   6.5340],
       

7it [00:04,  1.43it/s]
7it [00:09,  1.42s/it]


images saved
Evaluation for semantic segmentation - val set
mIoU is 6.48


100%|██████████| 7/7 [00:05<00:00,  1.37it/s]


KITTI 全景评价结果： {'pq': 0.0, 'sq': 0.0, 'rq': 0.0, 'iou_sum': 0.0, 'tp': 0, 'fp': 607, 'fn': 518}
Average loss: 9.626e-01
Epoch took 0:01:02.879319
ETA: 1:35:34.070254
-------------------------
Starting epoch 8
tensor([-27.0012, -26.2243, -26.2085,  ...,   5.5821,   5.8091,   5.8313],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  4,  8,  9, 10, 12, 13, 14, 15, 16, 17, 18], device='cuda:0')
Learning rate is set to: 1.000e-04
tensor([-28.6515, -27.7803, -27.5011,  ...,   6.3858,   6.4316,   7.0039],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 13, 14, 15, 16, 17, 18], device='cuda:0')
tensor([-27.6890, -27.6596, -26.8202,  ...,   4.1705,   4.2383,   4.3452],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 11, 12, 13, 14, 16, 17], device='cuda:0')
tensor([-28.3171, -28.2846, -27.7444,  ...,   3.8138,   3.8473,   4.2526],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 15, 16, 17], device='cuda:0

Exception in thread Thread-28 (_pin_memory_loop):
Traceback (most recent call last):
  File "/root/miniconda3/envs/LDMSeg/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/LDMSeg/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/LDMSeg/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/root/miniconda3/envs/LDMSeg/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/LDMSeg/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/LDMSeg/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", li

KeyboardInterrupt: 

 tensor([ 0,  8, 13, 14, 16, 17], device='cuda:0')
tensor([-30.3266, -29.9976, -29.4989,  ...,   4.4260,   4.4637,   4.5639],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 15, 16, 17], device='cuda:0')
tensor([-29.5236, -29.4850, -29.4186,  ...,   3.5876,   3.5988,   3.6526],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  2,  8, 10, 12, 13, 14, 16, 17], device='cuda:0')
tensor([-32.6295, -32.5828, -32.5282,  ...,   5.0371,   5.1463,   5.1819],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 13, 14, 16], device='cuda:0')
tensor([-28.2126, -28.0719, -27.9708,  ...,   3.8904,   4.0716,   4.2062],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 12, 13, 14, 16, 17, 18], device='cuda:0')
tensor([-29.1994, -29.1811, -29.0366,  ...,   5.1746,   5.3509,   5.4442],
       device='cuda:0', grad_fn=<Unique2Backward0>) tensor([ 0,  8, 10, 14, 16, 17], device='cuda:0')
tensor([-28.7764, -28.6695, -28.5976,  .